# SPDX-FileCopyrightText: Winni Neessen <wn@neessen.dev> et al
#
# SPDX-License-Identifier: MIT

coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 5%
        base: auto 
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: 90%
        base: auto
        if_ci_failed: error
        threshold: 5%

ignore:
  - "md4/"

comment:
  require_changes: true
